"""Add hash_status to email

Revision ID: 1004c4d77765
Revises: b9c086ac45f8
Create Date: 2025-02-12 22:54:51.191677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1004c4d77765'
down_revision = 'b9c086ac45f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.drop_column('hash_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hash_status', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
