"""Manually added first_name and last_name

Revision ID: 5462415f5fa5
Revises: 3ed60866651e
Create Date: 2025-03-06 10:29:47.760315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5462415f5fa5'
down_revision = '3ed60866651e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False,
               existing_server_default=sa.text("'Unknown'"))
        batch_op.alter_column('last_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False,
               existing_server_default=sa.text("'User'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('last_name',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'User'"))
        batch_op.alter_column('first_name',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'Unknown'"))

    # ### end Alembic commands ###
