"""Add role column to user table

Revision ID: 705380ccc408
Revises: 3836b7977767
Create Date: 2025-02-10 19:32:36.713539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '705380ccc408'
down_revision = '3836b7977767'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
