"""Add secretkey

Revision ID: 82708479fa63
Revises: 705380ccc408
Create Date: 2025-02-11 23:05:02.682466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82708479fa63'
down_revision = '705380ccc408'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secret_key', sa.String(length=16), nullable=True))
   
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('secret_key')

    # ### end Alembic commands ###
