"""Initial database setup

Revision ID: f282f4973f02
Revises: fc44faaf4ce1
Create Date: 2025-02-12 21:34:29.374345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f282f4973f02'
down_revision = 'fc44faaf4ce1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.drop_column('spf_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spf_status', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
