"""Initial database setup

Revision ID: fc44faaf4ce1
Revises: f7962970a85b
Create Date: 2025-02-12 19:34:30.021763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc44faaf4ce1'
down_revision = 'f7962970a85b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spf_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('hash_status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.drop_column('hash_status')
        batch_op.drop_column('spf_status')

    # ### end Alembic commands ###
